title: Site
form:
    fields:

        content:
            type: section
            title: Defaults
            underline: true

            fields:
                title:
                    type: text
                    label: Site Title
                    size: large
                    placeholder: "Site wide title"
                    help: Default title for your site

                description:
                    type: textarea
                    size: large
                    label: Description

                author.name:
                    type: text
                    size: large
                    label: Default Author

                author.email:
                    type: text
                    size: large
                    label: Default Email

                taxonomies:
                    type: text
                    size: large
                    label: Taxonomy Types
                    validate:
                    type: commalist

        blog:
            type: section
            title: Blog
            underline: true

            fields:
                blog.route:
                    type: text
                    size: large
                    label: Blog URL

                summary.size:
                    type: text
                    size: x-small
                    label: Summary Size
                    validate:
                    type: int
                    min: 0
                    max: 65536

        routes:
            type: section
            title: Routes
            underline: true

            fields:
                routes:
                    type: array
                    label: Custom
