jpg:
  type: image
  thumb: thumb-jpg.png
  mime: image/jpeg
jpeg:
  type: image
  thumb: thumb-jpeg.png
  mime: image/jpeg
png:
  type: image
  thumb: thumb-png.png
  mime: image/png
gif:
  type: image
  thumb: thumb-gif.png
  mime: image/gif

mp4:
  type: video
  thumb: thumb-mp4.png
  mime: video/mp4
mov:
  type: video
  thumb: thumb-mov.png
  mime: video/quicktime
m4v:
  type: video
  thumb: thumb-m4v.png
  mime: video/x-m4v
swf:
  type: video
  thumb: thumb-swf.png
  mime: video/x-flv

txt:
  type: file
  thumb: thumb-txt.png
  mime: text/plain
doc:
  type: file
  thumb: thumb-doc.png
  mime: application/msword
html:
  type: file
  thumb: thumb-html.png
  mime: text/html
pdf:
  type: file
  thumb: thumb-pdf.png
  mime: application/pdf
zip:
  type: file
  thumb: thumb-zip.png
  mime: application/zip
gz:
  type: file
  thumb: thumb-gz.png
  mime: application/gzip
