schemes:
  plugin:
    type: ReadOnlyStream
    paths:
      - user/plugins
      - system/plugins

#  asset:
#    type: ReadOnlyStream
#    paths:
#      - assets

#  cache:
#    type: ReadOnlyStream
#    paths:
#      - cache

#  log:
#    type: ReadOnlyStream
#    paths:
#      - logs

  page:
    type: ReadOnlyStream
    paths:
      - user/pages

  account:
    type: ReadOnlyStream
    paths:
      - user/accounts

  data:
    type: ReadOnlyStream
    paths:
      - user/data
