schemes:
  user:
    type: ReadOnlyStream
    paths:
      - user

#  asset:
#    type: ReadOnlyStream
#    paths:
#      - assets

  account:
    type: ReadOnlyStream
    paths:
      - user/accounts

  data:
    type: ReadOnlyStream
    paths:
      - user/data

  page:
    type: ReadOnlyStream
    prefixes:
      '/':
        - user/pages

  image:
    prefixes:
      '/':
        - user/images
        - system/images

  theme:
    prefixes:
      '/':
        - user/themes
        - system/themes
