schemes:
  asset:
    type: ReadOnlyStream
    paths:
      - assets

  image:
    type: ReadOnlyStream
    paths:
      - user/images

  user:
    type: ReadOnlyStream
    paths:
      - user

  page:
    type: ReadOnlyStream
    paths:
      - user/pages

  account:
    type: ReadOnlyStream
    paths:
      - user/accounts

  data:
    type: ReadOnlyStream
    paths:
      - user/data

  themes:
    type: ReadOnlyStream
    paths:
      - user/themes

