title: PLUGIN_ADMIN.SECURITY

form:
    validation: loose
    fields:

        security_section:
            type: section
            title: XSS Security
            underline: true

        xss_whitelist:
            type: selectize
            size: large
            label: Whitelist Permissions
            help: Users with these permissions will skip the XSS rules when saving content
            placeholder: 'admin.super'
            classes: fancy
            validate:
                type: commalist


        xss_rules:
            type: list
            label: Rules
            help: Be careful when tweaking these rules, a broken regex will break things badly!
            classes: compact
            fields:
                .label:
                    type: text
                    label: Label
                    validate:
                        required: true
                .enabled:
                    type: toggle
                    label: Rule Enabled
                    highlight: 1
                    options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
                    default: true
                    validate:
                        type: bool
                .regex:
                    type: text
                    label: Regex
                    validate:
                        required: true

