title: Configuration
validation: strict

form:
  fields:
    basics:
      type: section
      title: Basics
      underline: true

      fields:
        title:
          type: text
          label: Site Title
          placeholder: "Site wide title"
          help: Default title for your site

        base_url_absolute:
          type: text
          label: Absolute Base URL
          placeholder: "Override Absolute base URL (e.g. http://example.com)"
          help: You can provide a base URL to use rather than letting Grav guess what it is

        base_url_relative:
          type: text
          label: Relative Base URL
          placeholder: "Override Relative base URL (e.g. /subdirectory/site)"
          help: You can provide a base URL to use rather than letting Grav guess what it is

        pages.dateformat.short:
          type: select
          label: PHP date format
          help: "Set the PHP date format"
          default: 'jS M Y'
          options:
            'F jS \\a\\t g:ia': "January 1st at 11:59pm"
            'l jS of F g:i A': "Monday 1st of January at 11:59 PM"
            'D, m M Y G:i:s': "Mon, 01 Jan 2014 23:59:00"
            'd-m-y G:i': "01-01-14 23:59"
            'jS M Y': "10th Feb 2014"

        pages.dateformat.long:
          type: select
          label: Default date format
          help: "Set default date format rather than default for |date() filter"
          options:
            'F jS \a\t g:ia': "January 1st at 11:59pm"
            'l jS of F g:i A': "Monday 1st of January at 11:59 PM"
            'D, m M Y G:i:s': "Mon, 01 Jan 2014 23:59:00"
            'd-m-y G:i': "01-01-14 23:59"
            'jS M Y': "10th Feb 2014"

        pages.theme:
          type: themeselect
          label: Default Theme
          help: "Set the theme (defaults to 'default')"

    content:
      type: section
      title: Content
      underline: true

      fields:
        home.alias:
          type: pages
          label: Home page
          show_all: false
          show_modular: false
          show_root: false
          help: "The page that Grav will use as the default landing page"

        pages.order.by:
          type: select
          label: Default ordering
          options:
            default: Default - based on folder name
            folder: Folder - based on prefix-less folder name
            title: Title - based on title field in header
            date: Date - based on date field in header

        pages.order.dir:
          type: toggle
          label: Ordering direction
          default: asc
          options:
            asc: Ascending
            desc: Descending

        pages.list.count:
          type: text
          label: Item count
          help: "Default max pages count"
          validate:
            type: number
            min: 1

        pages.process:
          type: checkboxes
          label: Process
          default: [markdown: true, twig: true]
          options:
            markdown: Markdown
            twig: Twig
          use: keys

    events:
      type: section
      title: Events
      underline: true

      fields:
        pages.events.page:
          type: toggle
          label: Page events
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        pages.events.twig:
          type: toggle
          label: Twig events
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

    caching:
      type: section
      title: Caching
      underline: true

      fields:
        cache.enabled:
          type: toggle
          label: Caching
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        cache.check.pages:
          type: toggle
          label: Detect changes in pages
          help: Be careful changing this setting. If you disable this setting, Grav no longer automatically updates the pages when the underlaying files are changed.
          highlight: 1
          default: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        cache.prefix:
          type: text
          label: Cache prefix
          placeholder: "Derived from base URL (override by entering random string)"

        cache.driver:
          type: select
          label: Cache driver
          options:
            auto: Auto detect
            file: File
            apc: APC
            xcache: XCache
            memcache: MemCache
            memcached: MemCached
            wincache: WinCache

    twig:
      type: section
      title: Twig Templating
      underline: true

      fields:
        twig.cache:
          type: toggle
          label: Twig caching
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        twig.debug:
          type: toggle
          label: Twig debug
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        twig.auto_reload:
          type: toggle
          label: Detect changes
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        twig.autoescape:
          type: toggle
          label: Autoescape variables
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

    debugger:
      type: section
      title: Debugger
      underline: true

      fields:
        debugger.enabled:
          type: toggle
          label: Debugger
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        debugger.max_depth:
          type: select
          label: Detail levels
          placeholder: "How many nested levels to display for objects or arrays"
          options:
            1: 1 level
            2: 2 levels
            3: 3 levels
            4: 4 levels
            5: 5 levels
            6: 6 levels
            7: 7 levels
            8: 8 levels
            9: 9 levels
            10: 10 levels
          validate:
            type: number

        debugger.log.enabled:
          type: toggle
          label: Logging
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool

        debugger.log.timing:
          type: toggle
          label: Log timings
          highlight: 1
          options:
            1: Enabled
            0: Disabled
          validate:
            type: bool
